CREATE TABLE users(
  user_id SERIAL PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  firstname VARCHAR(255) NOT NULL,
  organization VARCHAR(50) NOT NULL,
  email VARCHAR(120) NOT NULL
);

CREATE TABLE reads(
  read_id SERIAL PRIMARY KEY,
  file1_filename VARCHAR(255) NOT NULL,
  file1_md5 VARCHAR(255) NOT NULL,
  file2_filename VARCHAR(255) NOT NULL,
  file2_md5 VARCHAR(255) NOT NULL,
  accession VARCHAR(255),
  instrument VARCHAR(255),
  library VARCHAR(255),
  library_other VARCHAR(255)
);

CREATE TABLE runs(
  run_id SERIAL PRIMARY KEY,
  user_id INT,
  sample_id INT,
  read_id INT,
  submitter_sample INT,
  submitter_database INT,
  starttime TIMESTAMP,
  active BOOLEAN,
  FOREIGN KEY (user_id)
    REFERENCES users (user_id)
);

CREATE TABLE samples(
  sample_id SERIAL PRIMARY KEY,
  pipeline_species VARCHAR(255) NOT NULL,
  primary_identifier VARCHAR(255) UNIQUE NOT NULL,
  case_id_type VARCHAR(255) NOT NULL,
  case_id_number INT,
  source_category VARCHAR(255) NOT NULL,
  source_species VARCHAR(255),
  sampling_reason VARCHAR(255),
  sampling_date_year SMALLINT,
  sampling_date_month SMALLINT,
  sampling_date_day SMALLINT,
  sample_received_date_year SMALLINT,
  sample_received_date_month SMALLINT,
  sample_received_date_day SMALLINT,
  owner_institute VARCHAR(255)  NOT NULL,
  owner_collection VARCHAR(255),
  location VARCHAR(255) NOT NULL,
  amr_phenotype VARCHAR(255),
  additional_information TEXT
);

CREATE TABLE software(
  software_id SERIAL PRIMARY KEY,
  container     VARCHAR(255) NOT NULL,
  time TIMESTAMP,
  software TEXT
);
CREATE TABLE amr_report( 
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255),
 "MLST_filename" TEXT,
 "MLST_matching_name" TEXT,
 "MLST_ST" TEXT,
 "MLST_alleleIDs" TEXT,
 "MLST_CC" TEXT,
 "resfinder_pointfinder_software_version" TEXT,
 "resfinder_database_download_date" DATE,
 "id_threshold_percentage_resfinder" NUMERIC(5,2),
 "min_length_threshold_percentage_resfinder" NUMERIC(5,2),
 "pointfinder_database_download_date" DATE,
 "id_threshold_percentage_pointfinder" NUMERIC(5,2),
 "min_length_threshold_percentage_pointfinder" NUMERIC(5,2),
 "resfinder_brief" TEXT,
 "resfinder_detailed" TEXT,
 "class_pheno_table_antibiotics_pheno_table" TEXT,
 "spectinomycin_aminocyclitol" TEXT,
 "unknown aminocyclitol_aminocyclitol" TEXT,
 "amikacin_aminoglycoside" TEXT,
 "apramycin_aminoglycoside" TEXT,
 "arbekacin_aminoglycoside" TEXT,
 "astromicin_aminoglycoside" TEXT,
 "butiromycin_aminoglycoside" TEXT,
 "butirosin_aminoglycoside" TEXT,
 "capreomycin_aminoglycoside" TEXT,
 "dibekacin_aminoglycoside" TEXT,
 "fortimicin_aminoglycoside" TEXT,
 "g418_aminoglycoside" TEXT,
 "gentamicin_aminoglycoside" TEXT,
 "gentamicin c_aminoglycoside" TEXT,
 "hygromycin_aminoglycoside" TEXT,
 "isepamicin_aminoglycoside" TEXT,
 "kanamycin_aminoglycoside" TEXT,
 "kanamycin a_aminoglycoside" TEXT,
 "kasugamycin_aminoglycoside" TEXT,
 "lividomycin_aminoglycoside" TEXT,
 "neomycin_aminoglycoside" TEXT,
 "netilmicin_aminoglycoside" TEXT,
 "paromomycin_aminoglycoside" TEXT,
 "ribostamycin_aminoglycoside" TEXT,
 "sisomicin_aminoglycoside" TEXT,
 "streptomycin_aminoglycoside" TEXT,
 "tobramycin_aminoglycoside" TEXT,
 "unknown aminoglycoside_aminoglycoside" TEXT,
 "chloramphenicol_phenicol" TEXT,
 "florfenicol_phenicol" TEXT,
 "unknown amphenicol_phenicol" TEXT,
 "unknown phenicol_phenicol" TEXT,
 "d-cycloserine_analog of d-alanine" TEXT,
 "unknown analog of d-alanine_analog of d-alanine" TEXT,
 "amoxicillin_beta-lactam" TEXT,
 "amoxicillin+clavulanic acid_beta-lactam" TEXT,
 "ampicillin_beta-lactam" TEXT,
 "ampicillin+clavulanic acid_beta-lactam" TEXT,
 "aztreonam_beta-lactam" TEXT,
 "cefazolin_beta-lactam" TEXT,
 "cefepime_beta-lactam" TEXT,
 "cefixime_beta-lactam" TEXT,
 "cefotaxime_beta-lactam" TEXT,
 "cefotaxime+clavulanic acid_beta-lactam" TEXT,
 "cefoxitin_beta-lactam" TEXT,
 "ceftaroline_beta-lactam" TEXT,
 "ceftazidime_beta-lactam" TEXT,
 "ceftazidime+avibactam_beta-lactam" TEXT,
 "ceftriaxone_beta-lactam" TEXT,
 "cefuroxime_beta-lactam" TEXT,
 "cephalothin_beta-lactam" TEXT,
 "cephalotin_beta-lactam" TEXT,
 "ertapenem_beta-lactam" TEXT,
 "imipenem_beta-lactam" TEXT,
 "meropenem_beta-lactam" TEXT,
 "penicillin_beta-lactam" TEXT,
 "piperacillin_beta-lactam" TEXT,
 "piperacillin+clavulanic acid_beta-lactam" TEXT,
 "piperacillin+tazobactam_beta-lactam" TEXT,
 "temocillin_beta-lactam" TEXT,
 "ticarcillin_beta-lactam" TEXT,
 "ticarcillin+clavulanic acid_beta-lactam" TEXT,
 "unknown beta-lactam_beta-lactam" TEXT,
 "bedaquiline_diarylquinoline" TEXT,
 "unknown diarylquinoline_diarylquinoline" TEXT,
 "sulfamethoxazole_folate pathway antagonist" TEXT,
 "trimethoprim_folate pathway antagonist" TEXT,
 "unknown folate pathway antagonist_folate pathway antagonist" TEXT,
 "fosfomycin_fosfomycin" TEXT,
 "unknown fosfomycin_fosfomycin" TEXT,
 "teicoplanin_glycopeptide" TEXT,
 "vancomycin_glycopeptide" TEXT,
 "unknown glycopeptide_glycopeptide" TEXT,
 "clofazimine_iminophenazine" TEXT,
 "unknown iminophenazine_iminophenazine" TEXT,
 "isoniazid_isonicotinic acid hydrazide" TEXT,
 "unknown isonicotinic acid hydrazide_isonicotinic acid hydrazide" TEXT,
 "clindamycin_lincosamide" TEXT,
 "lincomycin_lincosamide" TEXT,
 "unknown lincosamide_lincosamide" TEXT,
 "azithromycin_macrolide" TEXT,
 "carbomycin_macrolide" TEXT,
 "erythromycin_macrolide" TEXT,
 "oleandomycin_macrolide" TEXT,
 "spiramycin_macrolide" TEXT,
 "telithromycin_macrolide" TEXT,
 "tylosin_macrolide" TEXT,
 "unknown macrolide_macrolide" TEXT,
 "metronidazole_nitroimidazole" TEXT,
 "unknown nitroimidazole_nitroimidazole" TEXT,
 "linezolid_oxazolidinone" TEXT,
 "unknown oxazolidinone_oxazolidinone" TEXT,
 "tiamulin_pleuromutilin" TEXT,
 "unknown pleuromutilin_pleuromutilin" TEXT,
 "colistin_polymyxin" TEXT,
 "unknown polymyxin_polymyxin" TEXT,
 "mupirocin_pseudomonic acid" TEXT,
 "unknown pseudomonic acid_pseudomonic acid" TEXT,
 "ciprofloxacin_quinolone" TEXT,
 "fluoroquinolone_quinolone" TEXT,
 "nalidixic acid_quinolone" TEXT,
 "unknown quinolone_quinolone" TEXT,
 "unknown fluoroquinolone_quinolone" TEXT,
 "rifampicin_rifamycin" TEXT,
 "unknown rifamycin_rifamycin" TEXT,
 "para-aminosalicyclic acid_salicylic acid - anti-folate" TEXT,
 "unknown salicylic acid - anti-folate_salicylic acid - anti-folate" TEXT,
 "fusidic acid_steroid antibacterial" TEXT,
 "unknown steroid antibacterial_steroid antibacterial" TEXT,
 "dalfopristin_streptogramin a" TEXT,
 "pristinamycin iia_streptogramin a" TEXT,
 "quinupristin+dalfopristin_streptogramin a" TEXT,
 "unknown streptogramin a_streptogramin a" TEXT,
 "virginiamycin m_streptogramin a" TEXT,
 "pristinamycin ia_streptogramin b" TEXT,
 "quinupristin_streptogramin b" TEXT,
 "virginiamycin s_streptogramin b" TEXT,
 "unknown streptogramin b_streptogramin b" TEXT,
 "pyrazinamide_synthetic derivative of nicotinamide" TEXT,
 "unknown synthetic derivative of nicotinamide_synthetic derivative of nicotinamide" TEXT,
 "doxycycline_tetracycline" TEXT,
 "minocycline_tetracycline" TEXT,
 "tetracycline_tetracycline" TEXT,
 "tigecycline_tetracycline" TEXT,
 "unknown tetracycline_tetracycline" TEXT,
 "ethionamide_thioamide" TEXT,
 "unknown thioamide_thioamide" TEXT,
 "carbapenem_under_development" TEXT,
 "ceftiofur_under_development" TEXT,
 "cephalosporins_under_development" TEXT,
 "fluoroquinolone_under_development" TEXT,
 "norfloxacin_under_development" TEXT,
 "ethambutol_unspecified" TEXT,
 "unknown unspecified_unspecified" TEXT,
 "class_pheno_table_disinfectants_pheno_table" TEXT,
 "formaldehyde_aldehydes" TEXT,
 "unknown aldehyde_aldehydes" TEXT,
 "temperature_heat" TEXT,
 "hydrogen peroxide_peroxides" TEXT,
 "unknown peroxide_peroxides" TEXT,
 "benzylkonium chloride_quaternary ammonium compounds" TEXT,
 "cetylpyridinium chloride_quaternary ammonium compounds" TEXT,
 "chlorhexidine_quaternary ammonium compounds" TEXT,
 "ethidium bromide_quaternary ammonium compounds" TEXT,
 "unknown quaternary ammonium compound_quaternary ammonium compounds" TEXT,
 "pointfinder" TEXT,
 "ampC_promoter_size_53bp" TEXT,
 "folP" TEXT,
 "gyrA" TEXT,
 "gyrB" TEXT,
 "parC" TEXT,
 "parE" TEXT,
 "pmrA" TEXT,
 "pmrB" TEXT,
 "rpoB" TEXT,
 "16S_rrsB" TEXT,
 "16S_rrsC" TEXT,
 "16S_rrsH" TEXT,
 "23S" TEXT
);

CREATE TABLE samples_report( 
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255),
  "pipeline_species" TEXT,
  "samples_runSuccessfully" TEXT,
  "FastQ_Integrity_filesOK" TEXT,
  "innuca_samples_passQC" TEXT,
  "mismatch_passQC" TEXT,
  "first_FastQC_RunOK" TEXT,
  "first_FastQC_report_passQC" TEXT,
  "trimmomatic_passQC" TEXT,
  "reads_ConFindr_contamination_status" TEXT,
  "reads_kraken2_passQC" TEXT,
  "reads_serotypefinder_RunOK" TEXT,
  "reads_virulencefinder_RunOK" TEXT,
  "patho_typing_RunOK" TEXT,
  "reads_resfinder_RunOK" TEXT,
  "stx_seqtyping_RunOK" TEXT,
  "first_Coverage_passQC" TEXT,
  "trueCoverage_ReMatCh_passQC" TEXT,
  "second_Coverage_passQC" TEXT,
  "second_FastQC_RunOK" TEXT,
  "second_FastQC_report_passQC" TEXT,
  "quast_RunOK" TEXT,
  "SPAdes_RunOK" TEXT,
  "process_SPAdes_passQC" TEXT,
  "assembly_mapping_RunOK" TEXT,
  "process_am_passQC" TEXT,
  "pilon_RunOK" TEXT,
  "pilon_report_passQC" TEXT,
  "MLST_passQC" TEXT,
  "assembly_resfinder_RunOK" TEXT,
  "assembly_virulencefinder_RunOK" TEXT,
  "assembly_kraken2_passQC" TEXT,
  "insertsize_innu_RunOK" TEXT,
  "busco_RunOK" TEXT,
  "chewBBACA_passQC" TEXT
);

CREATE TABLE combine_samples_report(
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255),
  pipeline_species VARCHAR(255),
  number_bp_sequenced INT,
  number_reads_sequenced INT,
  reads_q_score_mean NUMERIC,
  bp_min_q30_number INT,
  bp_min_q30_percentage NUMERIC(5,2),
  min_reads_length INT,
  max_reads_length INT,
  reads_gc_percentage NUMERIC(5,2),
  reads_confindr_genus TEXT,
  reads_confindr_number_contaminated_snvs INT,
  reads_confindr_percentage_contaminated NUMERIC(5,2),
  reads_confindr_percentage_contaminated_sd NUMERIC(5,2),
  reads_confindr_bases_examined INT,
  reads_kraken_number_taxon_found INT,
  reads_kraken_percentage_unknown_fragments NUMERIC,
  reads_kraken_most_abundant_taxon TEXT,
  reads_kraken_percentage_most_abundant_taxon NUMERIC(5,2),
  reads_kraken_taxon_found_percentage TEXT,
  estimated_coverage_initial NUMERIC(5,2),
  truecoverage_absent_genes INT,
  truecoverage_multiple_alleles INT,
  truecoverage_sample_coverage NUMERIC(5,2),
  nreads_before_trimming INT,
  nreads_after_trimming INT,
  trimmed_percentage_bp_trimmomatic NUMERIC(5,2),
  estimated_coverage_second NUMERIC(5,2),
  pilon_final_assembly TEXT,
  pilon_changes INT,
  pilon_contigs_changed INT,
  pilon_average_contig_size NUMERIC,
  pilon_n50 INT,
  pilon_total_assembly_length INT,
  pilon_gc_content NUMERIC,
  pilon_num_contigs INT,
  quast_results_file TEXT,
  assembly_kraken_number_taxon_found INT,
  assembly_kraken_percentage_unknown_fragments NUMERIC(5,2),
  assembly_kraken_most_abundant_taxon TEXT,
  assembly_kraken_percentage_most_abundant_taxon NUMERIC(5,2),
  assembly_kraken_taxon_found_percentage TEXT,
  insert_size_mean NUMERIC,
  insert_size_sd NUMERIC,
  c_complete_gene_buscos_percentage NUMERIC(5,2),
  s_complete_single_copy_gene_buscos_percentage NUMERIC(5,2),
  d_complete_duplicated_gene_buscos_percentage NUMERIC(5,2),
  f_fragmented_gene_buscos_percentage NUMERIC(5,2),
  m_missing_gene_buscos_percentage NUMERIC(5,2),
  n_total_busco_groups_searched_number INT,
  mlst_matching_name TEXT,
  mlst_st TEXT,
  mlst_alleleids TEXT,
  mlst_cc TEXT,
  chewbbaca_exc_exact_matches INT,
  chewbbaca_inf_inferred_new_alleles INT,
  chewbbaca_lnf_loci_not_found INT,
  chewbbaca_plot_possible_loci_on_tip_of_contigs INT,
  chewbbaca_niph_non_informative_paralogous_hits INT,
  chewbbaca_alm_alleles_longer_than_matched_loci INT,
  chewbbaca_asm_alleles_shorter_than_matched_loci INT,
  chewbbaca_wgmlst_loci_found_number INT,
  chewbbaca_cgmlst_loci_found_number INT,
  chewbbaca_missing_cgmlst_targets_percentage NUMERIC(5,2),
  chewbbaca_good_cgmlst_targets_percentage NUMERIC(5,2)
);

CREATE TABLE log_report(
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255),
  sha_value_r1 TEXT,
  sha_value_r2 TEXT,
  md5_value_r1 TEXT,
  md5_value_r2 TEXT,
  pipeline_species TEXT,
  user_sample_submission TEXT,
  start_time_sample_submission TEXT,
  last_modified_time_sample_submission TEXT,
  user_database_submission TEXT,
  start_time_database_submission TEXT,
  last_modified_time_database_submission TEXT,
  confindr_software_version TEXT,
  confindr_database_download_date DATE,
  innuca_pipeline_version TEXT,
  innuca_software_versions TEXT,
  bowtie2_version TEXT,
  samtools_version TEXT,
  kraken2_version TEXT,
  fastqc_version TEXT,
  trimmomatic_version TEXT,
  spades_version TEXT,
  pilon_version TEXT,
  mlst2_version TEXT,
  innuca_kraken2_database_version TEXT,
  innuca_mlst_database_version TEXT,
  time_chewbbaca_allele_call_start TEXT,
  time_chewbbaca_database_submission_end TEXT,
  time_chewie_ns_last_syncronization  TEXT,
  chewbbaca_allele_call_software_version TEXT,
  chewbbaca_schema_version TEXT,
  chewbbaca_blast_score_ratio TEXT,
  chewbbaca_translation_table TEXT,
  chewbbaca_min_length  TEXT,
  chewbbaca_size_threshold TEXT,
  patho_typing_ecoli_software_version TEXT,
  stx_seqtyping_ecoli_software_version TEXT,
  sero_seqtyping_ecoli_software_version TEXT,
  patho_typing_yersinia_software_version TEXT,
  seqsero2_salmonella_software_version TEXT,
  sistr_salmonella_software_version TEXT,
  serotypefinder_software_version TEXT,
  serotypefinder_database_version TEXT,
  virulencefinder_software_version TEXT,
  virulencefinder_database_version TEXT,
  resfinder_software_version TEXT,
  resfinder_database_version TEXT
);


CREATE TABLE typing_report(
  run_date TIMESTAMP,
  active BOOLEAN,
  primary_identifier VARCHAR(255), 
  mlst_matching_name TEXT,
  mlst_st TEXT,
  mlst_alleleids TEXT,
  mlst_cc TEXT,
  pathotype TEXT,
  pathotype_genes_present TEXT,
  serotypefinder_software_version TEXT,
  serotypefinder_database_version TEXT,
  id_threshold_percentage_serotypefinder TEXT,
  min_length_threshold_percentage_serotypefinder TEXT,
  o_type_serotypefinder TEXT,
  h_type_serotypefinder TEXT,
  o_type_serotypefinder_long TEXT,
  h_type_serotypefinder_long TEXT,
  stx1_subtype_virulencefinder TEXT,
  stx2_subtype_virulencefinder TEXT,
  eae_virulencefinder TEXT,
  aggr_virulencefinder TEXT,
  who_risk_level_virulencefinder TEXT
);
